version: '3.6'
networks:
  default:
    external:
      name: spring-cloud
services:
  receiver-app:
    image: microservices-cloud/receiver-app
    ports:
      - "8090:8090"

  processor-app:
    image: microservices-cloud/processor-app

  files-api-app:
    image: microservices-cloud/files-api-app
    ports:
      - "8070:8070"

  orders-api-app:
    image: microservices-cloud/orders-api-app
    ports:
      - "8050:8050"

  customers-app:
    image: microservices-cloud/customers-app
    ports:
      - "8060:8060"
  web:
    image: microservices-cloud/web
    ports:
      - "4200:4200"